function Hd_fir = fir_filter
%FIR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 19-Apr-2022 13:45:12

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 96000; % 16980;  % Sampling Frequency

Fpass = 566;               % Passband Frequency
Fstop = 5660;              % Stopband Frequency
Dpass = 0.057501127785;    % Passband Ripple
Dstop = 5.0118723363e-05;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd_fir = dfilt.dffir(b);

% [EOF]
