function Hd_iir = iir_filter
%IIR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 19-Apr-2022 13:44:05

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 96000; % 16980;  % Sampling Frequency

Fpass = 566;         % Passband Frequency
Fstop = 5660;        % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 86;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd_iir = design(h, 'butter', 'MatchExactly', match);

% [EOF]
